name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: requisites
      run: sudo apt-get install libfreetype-dev x11proto-dev fontconfig libx11-dev libxft-dev 
    - name: make
      run: make
 
