name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: requisites
      run: sudo apt-get install libfreetype-dev x11proto-dev fontconfig libx11-dev libxft-dev python3-docutils
    - name: make
      run: make
    - name: make check
      run: make check
    - name: Install project
      run: sudo make install DESTDIR=$(pwd)/dist/debian
    - name: Get last tag
      id: get_tag
      run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
    - name: build package
      run: |
        TAG=$(echo ${{ steps.get_tag.outputs.tag }} | sed 's/^v//')
        sed -ei 's/VERSION/$TAG/' dist/debian/DEBIAN/control
        dpkg-deb --build dist/debian ../slterm_$TAG.deb
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: slterm-debian-package
        path: slterm_$TAG.deb 
