name: Create Release

on:
  #  push:
  #  tags:
  #    - '*'
  push:
    branches: [ "master" ]
  pull_request:
     branches: [ "master" ]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Binary using wget
        run: |
          wget https://github.com/michael105/static-bin/raw/refs/heads/main/xorg/slterm
          chmod a+x slterm
          mv slterm slterm_linux_amd64

